export const SET_LOGIN = 'SET_LOGIN';
export const SET_USERID = 'SET_USERID';
export const SET_USERINFO_AVATAR = 'SET_USERINFO_AVATAR';
export const SET_USERINFO_NAME = 'SET_USERINFO_NAME'
export const SET_USERINFO_INTRODUCTION = 'SET_USERINFO_INTRODUCTION'